server:
  port: 8030

spring:
  application:
    name: atomscat-consumer
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.12
    password: admin123456
    database: 1
    port: 6379

dubbo:
  registry:
    address: nacos://192.168.1.14:8848
    parameters:
      namespace: 5f5afe75-b943-40dc-ae5a-6f3e9ab24cf8
    check: false
  consumer:
    check: false