server:
  port: 8030

spring:
  application:
    name: atomscat-consumer
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.12
    password: admin123456
    database: 1
    port: 6379

dubbo:
  registry:
    address: nacos://192.168.1.14:8848
    parameters:
      namespace: e59784dc-e433-4b72-939a-fd5cff8cc0f2
    check: false
  consumer:
    check: false

seata:
  enabled: true
  application-id: atomscat-consumer
  tx-service-group: my_test_tx_group
  registry:
    nacos:
      server-addr: 192.168.1.14:8848
    type: nacos