###
POST http://127.0.0.1:8030/api/customer/info
Content-Type: application/json;charset=UTF-8

{
"name": "ABC"
}
###

###
POST http://127.0.0.1:8030/api/customer/setRedis
Content-Type: application/json;charset=UTF-8

{
  "name": "ABC"
}
###


###
POST http://127.0.0.1:8030/api/order/rushToBuy
Content-Type: application/json;charset=UTF-8

{
  "name": "ABC"
}
###




